Logger:
  Level: "debug"
  Output: "stdout"
Router:
  Port: 8081
  CORS: true
  BodyDump: true
  Duration: 1h
  UserIdKey: "user_id"
  RoleIdKey: "role_id"
  EmailKey: "email"
  AppName: "AppName"
  Version: "1.0.0"
SQL:
  write:
    Host: "localhost"
    Database: "puspeknubika"
    User: "app_user"
    Password: "superuser"
S3:
  upload:
    Endpoint: "localhost:9000"
    AccessKey: "minioadmin"
    SecretAccessKey: "minioadmin"
    BucketName: "content"
ApiClient:
  Timeout: 5s
Telemetry:
  Host: "http://project2_secret_token@localhost:14318?grpc=14317"
  AppName: "AppName"
  Version: "1.0.0"

SecretKey: "rahasia"
AuthExpire: "1h"
RefreshTokenExpire: "720h"
DatabaseUri: "mongodb://root:rootpassword@localhost:27017"
Database: "puspeknubika"
CourseCollection: "course"
CategoryCollection: "category"
AuditTrailCollection: "audit_trail"