version: "3.9"
services:
#  app:
#    build:
#      args:
#        GITHUB_TOKEN: "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"
#      dockerfile: Dockerfile
#      context: .
#    environment:
#      PUSPEKNUBIKA_SQL_WRITE_HOST: "db"
#    ports:
#      - '8081:8081'
#    depends_on:
#      db:
#        condition: service_started
#      minio:
#        condition: service_started
#    links:
#      - db
#      - minio
#    restart: on-failure
#    networks:
#      - backend

  db:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "puspeknubika"
      MYSQL_USER: "app_user"
      MYSQL_PASSWORD: "superuser"
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - ~/data:/var/lib/mysql
    networks:
      - backend

  mongo:
    image: mongo:latest
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - ~/mongo_data:/data/db
    networks:
      - backend

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: on-failure
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=content
    volumes:
      - ~/minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - '9000'
      - '9001'
    networks:
      - backend

networks:
  backend:
    external: true

volumes:
  db:
    driver: local